# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [16.15.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm install
    
    - name: build windows app
      if: matrix.os == 'windows-latest'
      run: |
        npm run electron:build
      
    - name: build mac app
      if: matrix.os == 'macos-latest'
      run: |
        npm run electron:build
        
    - name: build linux app
      if: matrix.os == 'ubuntu-latest'
      run: |
        npm run electron:build
    
    - name: cleanup artifacts
      run: |
          npx rimraf "dist_electron/!(*.exe|*.dmg|*.AppImage)"
          
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: dist_electron
