# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.1]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm install
      
    - name: build linux app
      run: |
        npm run electron:build
    
    - name: cleanup artifacts
      run: |
          npx rimraf "dist_electron/!(*.exe|*.dmg|*.AppImage)"
          
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-amd64
        path: dist_electron
        
  macos:
    runs-on: macos-10.15
    strategy:
      matrix:
        node-version: [16.15.1]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm install
      
    - name: build macos app
      run: |
        python --version
        npm run electron:build
    
    - name: cleanup artifacts
      run: |
          npx rimraf "dist_electron/!(*.exe|*.dmg|*.AppImage)"
          
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-amd64
        path: dist_electron
        
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.15.1]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm install
      
    - name: build windows app
      run: |
        npm run electron:build
    
    - name: cleanup artifacts
      run: |
          dir dist_electron | where {$_. name -notlike '*.exe*'} | Remove-Item -Recurse -force
          
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-amd64
        path: dist_electron
